var Config = require("config");
var Good = require("good");
var GoodConsole = require("good-console");
var Tilelive = require("../../../hapi-tilelive")
// Good (logging to the console)

exports.good = {

    register: Good,
    options: {
        reporters: [{
            reporter: GoodConsole,
            events: {
                //ops: "*",
                log: "*", // maps to the "log" event 
                response: "*", // maps to either the "response" or "tail" event
                error: "*", // maps to the "request-error" event
                request: "*" // maps to the hapi "request" event (generated by request.log())
            }
        }]
    }

};


exports.tilelive = {

    register: Tilelive,
    options: {
        //source: Config.get("tilesDir"),
        source: "/home/pvieira/tilemill-files/export",
        //routePath: "/tiles/{mapId}/{z}/{x}/{y}"
        routePath: "/tiles/{mapId}/{z}/{x}/{y}"
    }

};


