var SRIA = {
    "santamaria": "SRIA_SMA",
    "saomiguel": "SRIA_SMG",
    "terceira": "SRIA_TER",
    "faial": "SRIA_FAI",
    "pico": "SRIA_PIC",
    "saojorge": "SRIA_SJO",
    "graciosa": "SRIA_GRA",
    "flores": "SRIA_FLO",
    "corvo": "SRIA_COR"
};

var SRIT = {
    "santamaria": "SRIT_SMA",
    "saomiguel": "SRIT_SMG",
    "terceira": "SRIT_TER",
    "faial": "SRIT_FAI",
    "pico": "SRIT_PIC",
    "saojorge": "SRIT_SJO",
    "graciosa": "SRIT_GRA",
    "flores": "SRIT_FLO",
    "corvo": "SRIT_COR"
};


Cirac.layers = [

// PRECIPITACAO MEDIA ANUAL
{
    id: "pma-santamaria",
    name: "Santa Maria",
    description: "santa maria - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["santamaria"] + "/MapServer/WMSServer",
    layers: 25,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-saomiguel",
    name: "São Miguel",
    description: "sao miguel - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["saomiguel"] + "/MapServer/WMSServer",
    layers: 31,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-terceira",
    name: "Terceira",
    description: "terceira - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["terceira"] + "/MapServer/WMSServer",
    layers: 24,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-faial",
    name: "Faial",
    description: "faial - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["faial"] + "/MapServer/WMSServer",
    layers: 22,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-pico",
    name: "Pico",
    description: "pico - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["pico"] + "/MapServer/WMSServer",
    layers: 18,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-saojorge",
    name: "São Jorge",
    description: "saojorge - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["saojorge"] + "/MapServer/WMSServer",
    layers: 21,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-graciosa",
    name: "Graciosa",
    description: "graciosa - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["graciosa"] + "/MapServer/WMSServer",
    layers: 22,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-flores",
    name: "Flores",
    description: "flores - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["flores"] + "/MapServer/WMSServer",
    layers: 20,
    format: "image/png",
    transparent: true,
},
{
    id: "pma-corvo",
    name: "Corvo",
    description: "corvo - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_pma.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIA["corvo"] + "/MapServer/WMSServer",
    layers: undefined,
    format: "image/png",
    transparent: true,
},

// OCUPACAO SOLO
{
    id: "ocup-solo-santamaria",
    name: "Santa Maria",
    description: "santa maria - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["santamaria"] + "/MapServer/WMSServer",
    layers: [59],
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-saomiguel",
    name: "São Miguel",
    description: "sao miguel - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["saomiguel"] + "/MapServer/WMSServer",
    layers: 153,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-terceira",
    name: "Terceira",
    description: "terceira - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["terceira"] + "/MapServer/WMSServer",
    layers: 58,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-faial",
    name: "Faial",
    description: "faial - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["faial"] + "/MapServer/WMSServer",
    layers: 61,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-pico",
    name: "Pico",
    description: "pico - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["pico"] + "/MapServer/WMSServer",
    layers: 139,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-saojorge",
    name: "São Jorge",
    description: "saojorge - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["saojorge"] + "/MapServer/WMSServer",
    layers: 65,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-graciosa",
    name: "Graciosa",
    description: "graciosa - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["graciosa"] + "/MapServer/WMSServer",
    layers: undefined,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-flores",
    name: "Flores",
    description: "flores - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["flores"] + "/MapServer/WMSServer",
    layers: 60,
    format: "image/png",
    transparent: true,
},
{
    id: "ocup-solo-corvo",
    name: "Corvo",
    description: "corvo - desc",
    minzoom: 6,
    maxzoom: 14,
    legend: "<div><img src='/cartografia-app/legend_ocup-solo.jpg'></div>",
    tilejson: "2.0.0",
    attribution: "",
    isExclusive: false,
    zIndex: 5,

    isWMS: true,
    url: "http://sig-sraa.azores.gov.pt/ArcGIS/services/WMS/" + SRIT["corvo"] + "/MapServer/WMSServer",
    layers: 61,
    format: "image/png",
    transparent: true,
},
];
